### ISSUE TITLE
Summing an array and changing its key

### ISSUE THREAD

**Issue by z0mbiebrad** [Bradleytevans/Frontend-Code-Test#3]
Now update the `mutateArray` function so that the 'some_array' attribute in each item of the mutated array is changed to the sum of the array called 'some_total'
```
{
  'guest_type': 'crew',
  'first_name': 'Marco',
  'last_name': 'Burns',
  'room_no': 'A0073',
  'some_total': 13
},
```

**Comment by Bradleytevans** [comment]
Solved this by using  forEach loop to select each number in the array and add them together, then adding that sum to a new key of some_total.

**Comment by z0mbiebrad** [comment]
Solved this by using forEach loop to select each number in the array and add them together, then adding that sum to a new key of some_total.
